### PR TITLE
fix shell expansion error when no batteries are connected

### LINKED ISSUE #9: cron mail clutter when no batteries connected
/usr/share/battery-stats/collect-csv prints errors when no batteries are connected, resulting in cron mail clutter like

-----8<------
Subject: Cron root@localhost    if [ -x /usr/share/battery-stats/collect-csv ]; then /usr/share/battery-stats/collect-csv ; fi (failed)

/usr/share/battery-stats/collect-csv: line 86: cd: BAT*: No such file or directory
-----8<------

### PR DESCRIPTION
**Pull request by nachtgeist**
fixes #9

### CODE REVIEW

**Comment by jcromero** [comment]
It does not work if BAT\* is a symbolic link, like it is my case

**Comment by nachtgeist** [comment]
@jcromero: could you try this please:
`for bat in $(find . -maxdepth 1 -name "BAT*" -a \( -type d -o -type l \)); do`

**Comment by jcromero** [comment]
@nachtgeist I submited a pull request with other solution:
https://github.com/petterreinholdtsen/battery-stats/pull/13 

Both fixes work right

**Comment by nachtgeist** [comment]
yours is nicer :) thanks

**Pull request merged**
