### PR TITLE
Use proper default in python grapher

### PR DESCRIPTION
**Pull request by anarcat**
in the hope to make this script more standard, follow the convention of loading the file automatically

this also supports compression, so those logs can be rotated. i also did a little style cleanup while i was there.

### CODE REVIEW

**Comment by petterreinholdtsen** [comment]
Look good, but will this keep the ability to read the log file from stdin too?  I use it during debugging. :)

**Comment by petterreinholdtsen** [comment]
Another thing: If the default is good, the desktop file can be changed to drop the file argument.

**Comment by anarcat** [comment]
you may want to check the [fileinput module documentation](https://docs.python.org/3.5/library/fileinput.html). basically, it supports multiple files, compressed files and `-` for stdin.

so:
1. the default is good: it will look at the given `glob('/var/log/battery-stats.csv*')`
2. by default, it behaves as if `battery-log` was called (or in other words, like the default `battery-graph`), so the desktop file can indeed drop the argument
3. `fileinput` also supports using `-` to parse stdin, and supports gzip files

so i guess i should just add another patch to fix the desktop file here?

**Comment by anarcat** [comment]
so i rebased the branch and added a few more changes, including the desktop file change, hopefully that's good enough now!

**Comment by petterreinholdtsen** [comment]
Hm, after pulling these changes, the program do not work for me. :(

% src/battery-stats-graph /var/log/hjemmenett-battery-status.log
Traceback (most recent call last):
  File "src/battery-stats-graph", line 44, in <module>
    logfiles = fileinput.input(glob.glob(args.logfile), openhook=fileinput.hook_compressed)
  File "/usr/lib/python2.7/glob.py", line 27, in glob
    return list(iglob(pathname))
  File "/usr/lib/python2.7/glob.py", line 38, in iglob
    dirname, basename = os.path.split(pathname)
  File "/usr/lib/python2.7/posixpath.py", line 92, in split
    i = p.rfind('/') + 1
AttributeError: 'list' object has no attribute 'rfind'
% src/battery-stats-graph 
loading CSV file /var/log/battery-stats.csv\* with builtin CSV module
building data array
guessing expiry
/usr/lib/python2.7/dist-packages/numpy/lib/polynomial.py:587: RankWarning: Polyfit may be poorly conditioned
  warnings.warn(msg, RankWarning)
this battery will reach end of life (5%) in -7943 days, 10:15:41.964910, on 1994-06-27 03:46:55.108877
building graph
Traceback (most recent call last):
  File "src/battery-stats-graph", line 200, in <module>
    render_graph()
  File "src/battery-stats-graph", line 158, in render_graph
    if sys.stdout.isatty() and args.outfile == sys.stdout:
AttributeError: 'Namespace' object has no attribute 'outfile'
%

I'm running on Debian Jessie.

**Comment by anarcat** [comment]
right, sorry about that - fixed in #11.

**Pull request merged**
